"""This is an autogenerated file, please don't change it!"""

apis = {}

from controllers import sample as sample_controller
apis["/sample"] = sample_controller

from controllers import child_sample1 as child_sample1_controller
apis["/child_sample1"] = child_sample1_controller

from controllers import child_sample2 as child_sample2_controller
apis["/child_sample2"] = child_sample2_controller

from controllers import child_sample3 as child_sample3_controller
apis["/child_sample3"] = child_sample3_controller

